version: 1.0.0.{build}
configuration: Release
image:
- Visual Studio 2019
services: 
 - mssql2017
 - postgresql101

install:
  - cinst elasticsearch
  - appveyor-retry elasticsearch-service-x64 start

build_script:
- ps: >-
    .\Scripts\appveyor-build.ps1

test_script:
- ps: >-
    .\Scripts\appveyor-runTests.ps1